### ISSUE TITLE
List needed exports from the database

### ISSUE THREAD

**Issue by aartiukh** [NikitaKit1998/datakyt#11]
**Is your feature request related to a problem? Please describe.**
Think about what information from the database needs to be exported

**Describe the solution you'd like**
A Markdown table with description and list of fields to be filled.

**Comment by aartiukh** [comment]
| Name | Description | List of columns  |
|---------|------------------|----------------------|
|           |                     |                          |

**Comment by MykytaKyt** [comment]
| Name | Description | List of columns  |
|---------|------------------|----------------------|
| Employee list | Shows all info about employees | Employee name, email, phone, project, office |
| Employee list (by office) | Shows all info about employees filtered by office | Employee name, email, phone, project|
| Equipment by employees | Shows all equipment filtered by employee  | Employee Name, Equipment Name,  Type|
| Employee list (by project) | Shows all info about employees filtered by project | Employee name |
| Equipment by type | Shows the list of equipment filtered by type | Equipment name, Description, Serial Number |
| Software by employee  | Shows software filtered by employee | Software name, Product Key |
| Employee's  Furniture | Shows employee's furniture  | Furniture Name, Furniture Type |
| Reserved equipment | Shows the list of equipment in reserve | Name, Type, Serial Number, Description |
| Equipment on repair | Shows the list of equipment on repair |  Name, Type, Serial Number |
| Employee's equipment | Shows a list of equipment issued to employee | Equipment Name,  Type,  Serial Number |

**Comment by MykytaKyt** [comment]
@aartiukh
